from __future__ import annotations


def build_transform_messages(prompt_text: str) -> list[dict[str, str]]:
    return [
        {
            "role": "system",
            "content": "You are a high-level synthesis (HLS) expert. You are skilled at algorithm conversion. Please convert the algorithm description into HLS code. Just output the complete code.",
        },
        {"role": "user", "content": prompt_text},
    ]


def build_bug_fix_agent_prompt(buggy_code: str, error_log: str) -> str:
    return f"""You are given a piece of HLS code that contains bugs, the compiler error log, and the description of the buggy code. 
Your task is to debug the buggy code by analyzing the differences between it and the original code, using the error log to guide you.
Generate the COT debugging strategy through the buggy code, the code's description and error log.

**Instructions:**

1. **Debug the Code**:
    - **Identify Errors**: List the erroneous code line in the buggy code.
    - **Analyze Reasons**: Explain why each bug occurred, referencing the error log and the differences from the original code.
    - **Propose Fixes**: Specify the exact changes needed to fix each bug, including code modifications.

2. **Construct a Chain of Thought (CoT)**:
    - **Sequential Reasoning**: Address one error at a time, starting with syntax errors from the compiler.
    - **Hypothesis Formation**: Hypothesize why logical errors occur based on the error log and code comparison.
    - **Testing and Verification**: Validate hypotheses through analysis.
    - **Reflection**: Reflect on the findings after each step and plan the next steps.

3. **Output**:
    - **Chain of Thought (CoT)**: Write a detailed explanation of your debugging process.
    - **Bug Analysis in JSON Format**: Provide a structured summary as per the format below.
    - **No other explanations or conclusions**

**Inputs:**

Buggy Code:
```cpp
{buggy_code}
```

Vitis HLS Compiler Error Log:
```text
{error_log}
```

**Expected Output Format:**

Bug Analysis:
```json
    "bug_analysis": [
        "erroneous_code_line": [code line],
        "reason": "[Explanation of why the bug occurred]",
        "modification_actions": [
            "action": "[Specific modification to be made]",
            "reason": "[Reason for the modification]"
        // Add more actions if necessary
        ]
    // Add more error analyses if necessary
    ]
```
Please ensure that the JSON is properly formatted and valid.
"""


def build_debug_analysis_messages(prompt_text: str) -> list[dict[str, str]]:
    return [
        {
            "role": "system",
            "content": """You are an expert in High-Level Synthesis (HLS) programming. 
                Your primary task is to identify and debug HLS-incompatible errors in regular C/C++ programs. You will be provided with:
                - **Buggy Code**: A C/C++ program containing HLS-incompatible errors.
                - **Compiler Error Log**: The error messages generated by the Vitis HLS compiler.""",
        },
        {"role": "user", "content": prompt_text},
    ]


def build_fixer_prompt(buggy_code: str, debug_suggestion: str) -> str:
    return f"""Strictly follow the modification suggestions: {debug_suggestion}
correct the code with errors: {buggy_code}
require that the output only has the modified code, no other explanations.
                        """


def build_score_prompt(origin_code: str, debug_suggestion_0: str, debug_suggestion_1: str, debug_suggestion_2: str) -> str:
    return f"""Combine the compilation information of the modified code to analyze the quality of the code modifications. 
Score each of the four inputs separately from 0 to 10, ensuring that the scores are all different. 
The unmodified code is as follows: {origin_code}. The debugging suggestions are:
A: {debug_suggestion_0}
B: {debug_suggestion_1}
C: {debug_suggestion_2}
Output the code debugging suggestion with the highest score and explain why it received the highest score. 
No additional explanation is needed.
    """


def build_debug_score_messages(prompt_text: str) -> list[dict[str, str]]:
    return [{"role": "user", "content": prompt_text}]


def build_debug_modify_messages(prompt_text: str) -> list[dict[str, str]]:
    return [
        {"role": "system", "content": "You are a code correction tool."},
        {"role": "user", "content": prompt_text},
    ]


def build_dse_prompt(hls_code: str, hls_code_ppa: str, loop_array_info: str) -> str:
    return f"""Your task is to optimize the following HLS kernel by inserting `#pragma` directives 
to enhance loops and arrays for lower latency and relatively low resource utilization. 
You may use the following pragma types:

- Loop Pipeline
- Loop Unroll
- Array Partition

Provided code:
{hls_code}

Current latency and hardware resource utilization:
{hls_code_ppa}

Loop and array information:
{loop_array_info}

Please suggest pragma modifications, specifying where to insert them and the reasoning behind each. 
Provide only the suggestions without additional explanations or formatting.

**Expected Output Format**:

Detailed Reasoning:
```text
[Your step-by-step analysis here]
```

Optimization Strategies:
```json
    "Optimization Strategies": [
        "Code Segment Before Optimization (Loop/Array)": "[Code line before optimization]",
        "Code Segment After Optimization (Loop/Array)": "[Code line after inserting the pragma]",
        "Reason": "[Explanation of why this pragma was inserted]",
        "Result Analysis":
        "Impact of Inserting This Pragma on PPA": "[Description of the impact on Performance, Power, and Area]",
        "Reason": "[Explanation of why this impact occurred based on the performance analysis]"
    // Add more entries if necessary
    ]
```
    """


def build_optimize_analysis_messages(prompt_text: str) -> list[dict[str, str]]:
    return [
        {
            "role": "system",
            "content": """You are an expert proficient in HLS algorithm optimization,
                improving algorithm PPA through inserting pragmas into arrays and loops in HLS code.""",
        },
        {"role": "user", "content": prompt_text},
    ]


def build_code_modify_prompt(origin_code: str, insertion_suggestion: str) -> str:
    return f"""Strictly follow the modification suggestions: {insertion_suggestion}
modify the code: {origin_code}.
Please note that when optimizing arrays or loops, 
the #pragma should be inserted immediately after the statement to be optimized, not before it.
Require that the output only has the modified code, no other explanations, 
and the code should not be in markdown format.
    """


def build_optimize_modify_messages(prompt_text: str) -> list[dict[str, str]]:
    return [
        {"role": "system", "content": "You are a useful tool."},
        {"role": "user", "content": prompt_text},
    ]
